### ISSUE TITLE
Arm64 support for installation on Ubuntu 20.10

### ISSUE THREAD

**Issue by PaulAB10-gh** [CoolerMasterTechnology/Pi-Tool#5]
Pi-tool will currently not install on Ubuntu 20.10 due to unmet dependencies

=== Pi Tool installation ===
 Installing...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxss-dev is already the newest version (1:1.2.3-1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'pi-tool:armhf' instead of '/tmp/pi-tool_0.3.0_armv7l.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 pi-tool:armhf : Depends: libnotify4:armhf but it is not installable
                 Depends: libappindicator1:armhf but it is not installable
                 Depends: libxtst6:armhf but it is not installable
                 Depends: libnss3:armhf but it is not installable
                 Depends: lxterminal:armhf but it is not installable
                 Depends: libraspberrypi-bin:armhf but it is not installable
E: Unable to correct problems, you have held broken packages.
 
 Done!

**Comment by mntns** [comment]
While Ubuntu isn't officially supported, we will look into `arm64` support very soon, so you might be successful in running it on your setup then! I'd kindly redirect you to the issue for 64-bit support (https://github.com/CoolerMasterTechnology/Pi-Tool/issues/8) and close this issue for now.
